// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'tokens/spacing';
import colors from 'tokens/colors';
import borderWidths from 'tokens/borderWidths';
import radii from 'tokens/radii';

const CheckboxCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: ${spacing.medium};
  background-color: ${colors.white};
  border-width: ${borderWidths.hairline};
  border-color: ${colors.black};
  border-radius: ${radii.circle};
  background-color: ${colors.green2};

  &.Normal {
  }

`;

export default CheckboxCss;