// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'tokens/spacing.mjs';
import colors from 'tokens/colors.mjs';
import borderWidths from 'tokens/borderWidths.mjs';
import radii from 'tokens/radii.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';

const CheckboxCss = `width: 100%;
box-sizing: border-box;
padding-top: 2.8125rem;
height: ${spacing.medium};
border: 0;
border-style: solid;
border-width: ${borderWidths.hairline};
border-color: ${colors.black};
border-radius: ${radii.circle};
color: ${colors.black};
font-size: ${fontSizes.sub};
font-family: ${fontFamilies.regular};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.xs};
text-align: left;

&.Normal {
  background-color: ${colors.white};
}

&:checked {
  background-color: ${colors.green2};
}

`;

export default CheckboxCss;