// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors.mjs';
import borderWidths from 'tokens/borderWidths.mjs';

const SliderCss = ` width: 100%;
box-sizing: border-box;
height: 4;
background-color: ${colors.gray3};
border: 0;
border-style: solid;
border-width: ${borderWidths.fat};
border-color: ${colors.gray3};
`;

export default SliderCss;