// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';

const H6Css = ` color: ${colors.black};
font-size: ${fontSizes.h6};
font-family: ${fontFamilies.bold};
font-weight: ${fontWeights.bold};
line-height: ${lineHeights.xs};
text-align: left;
text-transform: uppercase;
`;

export default H6Css;