// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';

const H2Css = ` color: ${colors.black};
font-size: ${fontSizes.h2};
font-family: ${fontFamilies.regular};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.s};
text-align: left;
`;

export default H2Css;