// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import borderWidths from 'tokens/borderWidths.mjs';
import shadows from 'tokens/shadows.mjs';

const ShadowtesterCss = ` width: 100%;
box-sizing: border-box;
height: 232;
background-color: rgba(196, 196, 196, 1);
border: 0;
border-style: solid;
border-width: ${borderWidths.hairline};
box-shadow: ${shadows.deep};
`;

export default ShadowtesterCss;