// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors';
import fontSizes from 'tokens/fontSizes';
import fontFamilies from 'tokens/fontFamilies';
import fontWeights from 'tokens/fontWeights';
import lineHeights from 'tokens/lineHeights';

const H2Css = `
color: ${colors.black};
font-size: ${fontSizes.h2};
font-family: ${fontFamilies.bold};
font-family: ${fontFamilies.medium};
font-family: ${fontFamilies.regular};
font-family: ${fontFamilies.light};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.s};
text-align: left;
`;

export default H2Css;