// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
 "hairline": "1px",
 "regular": "2px",
 "fat": "4px",
 "chunky": "8px"
} as const;

export default borderWidths;