// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const durations = {
 "short": 0.15,
 "medium": 0.25,
 "long": 0.6,
 "veryLong": 1
} as const;

export default durations;