// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const easings = {
 "easeInSine": "cubic-bezier(0.12, 0, 0.39, 0)",
 "easeOutSine": "cubic-bezier(0.61, 1, 0.88, 1)",
 "easeInOutSine": "cubic-bezier(0.37, 0, 0.63, 1)"
} as const;

export default easings;