// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "light": "Helvetica Neue",
 "regular": "Helvetica Neue",
 "medium": "Helvetica Neue",
 "bold": "Helvetica Neue"
} as const;

export default fontFamilies;