// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
 "regular": "0em",
 "wide": "0.05em",
 "tight": "-0.045em"
} as const;

export default letterSpacings;