// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const lineHeights = {
 "l": "1.65",
 "m": "1.45",
 "s": "1.35",
 "xs": "1.00"
} as const;

export default lineHeights;