// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "tiny": "0.5rem",
 "small": "1rem",
 "medium": "2rem",
 "big": "3rem",
 "large": "4rem",
 "huge": "6rem"
} as const;

export default spacing;