// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'tokens/spacing.mjs';
import colors from 'tokens/colors.mjs';
import borderWidths from 'tokens/borderWidths.mjs';
import radii from 'tokens/radii.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';
import letterSpacings from 'tokens/letterSpacings.mjs';

const ButtonCss = `width: 100%;
box-sizing: border-box;
height: ${spacing.big};
border: 0;
border-style: solid;
border-width: ${borderWidths.hairline};
border-color: ${colors.blue2};
border-radius: ${radii.soft};
color: ${colors.white};
font-size: ${fontSizes.paragraph};
font-family: ${fontFamilies.bold};
font-weight: ${fontWeights.bold};
line-height: ${lineHeights.xs};
letter-spacing: ${letterSpacings.wide};
text-align: center;
text-transform: uppercase;

&.Error {
  background-color: ${colors.red};
}

&.Warning {
  background-color: ${colors.orange};
}

&.Normal {
  background-color: ${colors.blue1};
}

`;

export default ButtonCss;