// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from '../../../tokens/spacing';
import borderWidths from '../../../tokens/borderWidths';
import colors from '../../../tokens/colors';
import radii from '../../../tokens/radii';
import fontSizes from '../../../tokens/fontSizes';
import fontFamilies from '../../../tokens/fontFamilies';
import fontWeights from '../../../tokens/fontWeights';
import lineHeights from '../../../tokens/lineHeights';
import letterSpacings from '../../../tokens/letterSpacings';

const ButtonCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: ${spacing.big};
  border-width: ${borderWidths.hairline};
  border-color: ${colors.blue2};
  border-radius: ${radii.soft};
  color: ${colors.white};
  font-size: ${fontSizes.paragraph};
  font-family: ${fontFamilies.bold};
  font-family: ${fontFamilies.medium};
  font-family: ${fontFamilies.regular};
  font-family: ${fontFamilies.light};
  font-weight: ${fontWeights.bold};
  line-height: ${lineHeights.xs};
  letter-spacing: ${letterSpacings.wide};
  text-align: center;
  text-transform: uppercase;

  &.Normal {
    padding-left: ${spacing.small};
    padding-right: ${spacing.small};
    background-color: ${colors.blue1};
    &:disabled {
      background-color: ${colors.gray1};
    }
  }

  &.Warning {
    padding-left: ${spacing.small};
    padding-right: ${spacing.small};
    background-color: ${colors.orange};
    &:disabled {
      background-color: ${colors.gray1};
    }
    &:hover {
      background-color: ${colors.yellow};
    }
  }

  &.Error {
    padding-left: ${spacing.small};
    padding-right: ${spacing.small};
    background-color: ${colors.red};
    &:hover {
      background-color: rgba(123; 34; 34; 1);
    }
  }

`;

export default ButtonCss;
