// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';
import spacing from 'tokens/spacing.mjs';
import borderWidths from 'tokens/borderWidths.mjs';
import radii from 'tokens/radii.mjs';
import shadows from 'tokens/shadows.mjs';

const SelectCss = ` color: ${colors.gray1};
font-size: ${fontSizes.sub};
font-family: ${fontFamilies.regular};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.xs};
text-align: left;
width: 100%;
box-sizing: border-box;
padding-left: ${spacing.small};
padding-right: ${spacing.small};
height: ${spacing.medium};
background-color: ${colors.white};
border: 0;
border-style: solid;
border-width: ${borderWidths.regular};
border-color: ${colors.blue2};
border-radius: ${radii.soft};
box-shadow: ${shadows.soft};
`;

export default SelectCss;