// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'tokens/spacing.mjs';
import colors from 'tokens/colors.mjs';
import borderWidths from 'tokens/borderWidths.mjs';
import radii from 'tokens/radii.mjs';
import shadows from 'tokens/shadows.mjs';
import fontSizes from 'tokens/fontSizes.mjs';
import fontFamilies from 'tokens/fontFamilies.mjs';
import fontWeights from 'tokens/fontWeights.mjs';
import lineHeights from 'tokens/lineHeights.mjs';

const InputCss = `width: 100%;
box-sizing: border-box;
padding-left: ${spacing.small};
padding-right: ${spacing.small};
height: ${spacing.big};
border: 0;
border-style: solid;
border-width: ${borderWidths.regular};
border-color: ${colors.black};
border-radius: ${radii.rounded};
box-shadow: ${shadows.soft};
font-size: ${fontSizes.paragraph};
font-family: ${fontFamilies.regular};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.xs};
text-align: left;

&:invalid {
  color: ${colors.red};
  background-color: ${colors.black};
}

&:placeholder {
  color: ${colors.gray2};
  background-color: ${colors.white};
}

&.Normal {
  color: ${colors.black};
  background-color: ${colors.white};
}

`;

export default InputCss;