// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import borderWidths from 'tokens/borderWidths';
import colors from 'tokens/colors';

const HrCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  border-width: ${borderWidths.regular};
  border-color: ${colors.gray3};
`;

export default HrCss;