// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import fontSizes from '../../../tokens/fontSizes';
import fontFamilies from '../../../tokens/fontFamilies';
import fontWeights from '../../../tokens/fontWeights';
import lineHeights from '../../../tokens/lineHeights';
import spacing from '../../../tokens/spacing';
import colors from '../../../tokens/colors';
import borderWidths from '../../../tokens/borderWidths';
import shadows from '../../../tokens/shadows';

const FormCss = `
  color: rgba(0; 0; 0; 1);
  font-size: ${fontSizes.paragraph};
  font-family: ${fontFamilies.bold};
  font-family: ${fontFamilies.medium};
  font-family: ${fontFamilies.regular};
  font-family: ${fontFamilies.light};
  font-weight: ${fontWeights.regular};
  line-height: ${lineHeights.xs};
  text-align: left;
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  padding-top: ${spacing.small};
  padding-bottom: ${spacing.small};
  padding-left: ${spacing.small};
  padding-right: ${spacing.small};
  height: 189;
  background-color: ${colors.white};
  border-width: ${borderWidths.hairline};
  border-color: ${colors.gray1};
  box-shadow: ${shadows.deep};
`;

export default FormCss;
