// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors.mjs';
import borderWidths from 'tokens/borderWidths.mjs';
import shadows from 'tokens/shadows.mjs';

const FormCss = ` width: 100%;
box-sizing: border-box;
height: 600;
background-color: ${colors.white};
border: 0;
border-style: solid;
border-width: ${borderWidths.hairline};
border-color: ${colors.gray1};
box-shadow: ${shadows.deep};
`;

export default FormCss;